server:
  port: 8080

token:
  token_ttl: 1m
  token_key: petersburgSalt
  refreshToken_ttl: 1440h

db_tables:
  crud: AbuseEntity
  auth: users
  tokens: refresh_tokens

hashphrase: somesalte

logdb:
  ip: 
  port: