server:
  port: 8080

token:
  token_ttl: 140h
  token_key: petersburgSalt
  refreshToken_ttl: 1440h

db_tables:
  crud: AbuseEntity
  auth: users
  tokens: refresh_tokens

hashphrase: somesalte

rabbitmq:
  url: amqp://guest:guest@localhost:5672/
  queueName: logs